from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Portal_EDU.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^crear/', 'schools.views.crear', name='crear'),
    url(r'^academic-calendars/', include('academic_calendars.urls')),
    url(r'^assignments/', include('assignments.urls')),
    url(r'^', include('authentication.urls')),    
    url(r'^blood-types/', include('blood_types.urls')),
    url(r'^classrooms/', include('classrooms.urls')),
    url(r'^contact-types/', include('contact_types.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'^entrance-schedules/', include('entrance_schedules.urls')),
    url(r'^extra-curricular-activities/', include('extra_curricular_activities.urls')),
    url(r'^extra-curricular-activity-types/', include('extra_curricular_activity_types.urls')),
    url(r'^genres/', include('genres.urls')),
    url(r'^grade-names/', include('grade_names.urls')),
    url(r'^grades/', include('grades.urls')),
    url(r'^incharge-appointments/', include('incharge_appointments.urls')),
    url(r'^incharge-types/', include('incharge_types.urls')),
    url(r'^incharges/', include('incharges.urls')),
    url(r'^levels/', include('levels.urls')),
    url(r'^medical-backgrounds/', include('medical_backgrounds.urls')),
    url(r'^modules/', include('modules.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^planification-types/', include('planification_types.urls')),
    url(r'^planifications/', include('planifications.urls')),
    url(r'^schedules/', include('schedules.urls')),
    url(r'^schools/', include('schools.urls')),
    url(r'^sections/', include('sections.urls')),
    url(r'^staff-activities/', include('staff_activities.urls')),
    url(r'^staff-appointments/', include('staff_appointments.urls')),
    url(r'^staff-entrance-reports/', include('staff_entrance_reports.urls')),
    url(r'^staff-entrance-schedules/', include('staff_entrance_schedules.urls')),
    url(r'^staff-meeting-schedules/', include('staff_meeting_schedules.urls')),
    url(r'^staff-types/', include('staff_types.urls')),
    url(r'^staffs/', include('staffs.urls')),
    url(r'^student-control-list/', include('student_control_list.urls')),
    url(r'^student-reports', include('student_reports.urls')),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^tasks/', include('tasks.urls')),    
    
)
